name: plantify_production

services:
  grpcserver:
    image: grpcserver:latest
    container_name: grpcserver
    build:
      context: .
      dockerfile: ./GrpcService/Dockerfile.local
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:10081
    user: root
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "10081:10081"
    networks:
      plantify-network:
        aliases:
          - grpcserver
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: plantify
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: plantifydev
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    networks:
      - plantify-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d plantify"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  plantify-network:
    external: true
    name: plantify-network