services:
  datadev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: datadev
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: sleep infinity
    user: root
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
  grpcserver:
    build:
      context: .
      dockerfile: ./GrpcService/Dockerfile
    container_name: grpcserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:10081
    user: root
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "10081:10081"
    networks:
      backend:
        aliases:
          - grpcserver
  postgres:
    image: postgres:17-alpine
    container_name: task-postgres
    environment:
      POSTGRES_DB: plantify
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: plantifydev
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d plantify"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  backend:
    name: plantify-backend
    driver: bridge
