// <auto-generated />
using EFC.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFC.Migrations
{
    [DbContext(typeof(PlantifyContext))]
    [Migration("20260427230229_LightPeriodForPlant")]
    partial class LightPeriodForPlant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.plant.AirHumidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlantMAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlantMAC");

                    b.ToTable("AirHumidity");
                });

            modelBuilder.Entity("Entities.plant.LightIntensity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlantMAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlantMAC");

                    b.ToTable("LightIntensities");
                });

            modelBuilder.Entity("Entities.plant.Plant", b =>
                {
                    b.Property<string>("MAC")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OptimalAirHumidity")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalLightIntensity")
                        .HasColumnType("double precision");

                    b.Property<long>("OptimalLightPeriod")
                        .HasColumnType("bigint");

                    b.Property<double>("OptimalSoilHumidity")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperature")
                        .HasColumnType("double precision");

                    b.Property<int>("Scale")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MAC");

                    b.HasIndex("Username");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Entities.plant.SoilHumidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlantMAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlantMAC");

                    b.ToTable("SoilHumidity");
                });

            modelBuilder.Entity("Entities.plant.Temperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlantMAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlantMAC");

                    b.ToTable("Temperatures");
                });

            modelBuilder.Entity("Entities.plant.WaterIntake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlantMAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlantMAC");

                    b.ToTable("WaterIntakes");
                });

            modelBuilder.Entity("Entities.plant.AirHumidity", b =>
                {
                    b.HasOne("Entities.plant.Plant", "Plant")
                        .WithMany("AirHumidities")
                        .HasForeignKey("PlantMAC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Entities.plant.LightIntensity", b =>
                {
                    b.HasOne("Entities.plant.Plant", "Plant")
                        .WithMany("LightIntensities")
                        .HasForeignKey("PlantMAC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Entities.plant.Plant", b =>
                {
                    b.HasOne("Entities.User", "Owner")
                        .WithMany("Plants")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Entities.plant.SoilHumidity", b =>
                {
                    b.HasOne("Entities.plant.Plant", "Plant")
                        .WithMany("SoilHumidities")
                        .HasForeignKey("PlantMAC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Entities.plant.Temperature", b =>
                {
                    b.HasOne("Entities.plant.Plant", "Plant")
                        .WithMany("Temperatures")
                        .HasForeignKey("PlantMAC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Entities.plant.WaterIntake", b =>
                {
                    b.HasOne("Entities.plant.Plant", "Plant")
                        .WithMany("WaterIntakes")
                        .HasForeignKey("PlantMAC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("Entities.plant.Plant", b =>
                {
                    b.Navigation("AirHumidities");

                    b.Navigation("LightIntensities");

                    b.Navigation("SoilHumidities");

                    b.Navigation("Temperatures");

                    b.Navigation("WaterIntakes");
                });
#pragma warning restore 612, 618
        }
    }
}
