// <auto-generated />
using System;
using EFC.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFC.Migrations
{
    [DbContext(typeof(PlantifyContext))]
    partial class PlantifyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.plant.Plant", b =>
                {
                    b.Property<string>("MAC")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OptimalAirHumidity")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalLightIntensity")
                        .HasColumnType("double precision");

                    b.Property<long>("OptimalLightPeriod")
                        .HasColumnType("bigint");

                    b.Property<double>("OptimalSoilHumidity")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalTemperature")
                        .HasColumnType("double precision");

                    b.Property<int>("Scale")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MAC");

                    b.HasIndex("Username");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Entities.plant.SensorData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("AirHumidity")
                        .HasColumnType("double precision");

                    b.Property<double>("LightIntensity")
                        .HasColumnType("double precision");

                    b.Property<string>("PlantMAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SoilHumidity")
                        .HasColumnType("double precision");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlantMAC");

                    b.ToTable("SensorDatas");
                });

            modelBuilder.Entity("Entities.plant.Watering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastWaterTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlantMAC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PredictedFutureWaterTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PumpTimeInSeconds")
                        .HasColumnType("integer");

                    b.Property<double>("WaterLevel")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PlantMAC");

                    b.ToTable("Waterings");
                });

            modelBuilder.Entity("Entities.plant.Plant", b =>
                {
                    b.HasOne("Entities.User", "Owner")
                        .WithMany("Plants")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Entities.plant.SensorData", b =>
                {
                    b.HasOne("Entities.plant.Plant", "Plant")
                        .WithMany("SensorDatas")
                        .HasForeignKey("PlantMAC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Entities.plant.Watering", b =>
                {
                    b.HasOne("Entities.plant.Plant", "Plant")
                        .WithMany("Waterings")
                        .HasForeignKey("PlantMAC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("Entities.plant.Plant", b =>
                {
                    b.Navigation("SensorDatas");

                    b.Navigation("Waterings");
                });
#pragma warning restore 612, 618
        }
    }
}
